networks:
  blank:
services:
  database:
    image: mariadb:10.11.6
    restart: unless-stopped
    networks:
      blank:
        aliases:
          - db
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    depends_on:
      - database
      - mail-server
    networks:
      blank:
        aliases:
          - keycloak
    ports:
      - "48080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://db:3306/keycloak?characterEncoding=UTF-8
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak1234
    command:
      - --verbose
      - start-dev
      - --log-console-format='%d{dd-MM-yyyy HH:mm:SSS} [%t] %-5p %c{2.} %s [traceId=%X{traceId}] %e%n'
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--hostname-strict=false"

    volumes:
      - ./export:/opt/keycloak/data/export

  mail-server:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    networks:
      blank:
        aliases:
          - mailhog
    ports:
      - "41025:1025"
      - "48025:8025"